Update .install

diff --git a/.install b/.install
--- a/.install
+++ b/.install
@@ -1,5 +1,12 @@
 #!/data/data/com.termux/files/usr/bin/bash
 
+echo
+
+if [ ! -d "/data/data/com.termux.api" ]; then
+    echo -e "\ncom.termux.api app is not installed\nPlease install it first\n"
+    exit 1
+fi
+
 arch=$(uname -m)
 
 if [ "$arch" = "aarch64" ]; then
@@ -11,18 +18,55 @@ else
     exit 1
 fi
 
+echo -ne "\rurl check ..."
+
 main_repo=$(grep -E '^deb ' /data/data/com.termux/files/usr/etc/apt/sources.list | awk '{print $2}' | head -n 1)
 
-while true; do
-    curl -s $main_repo > /dev/null
-    if [ $? -eq 0 ]; then
-        echo -e "\n\033[32mapt update...\033[0m"
-        apt update > /dev/null 2> >(grep -v "apt does not have a stable CLI interface") && break
+curl -s --retry 4 $main_repo > /dev/null
+exit_code=$?
+
+if [ $exit_code -eq 6 ]; then
+    echo -e "\nRequest to $main_repo failed. Please check your internet connection.\n"
+    exit 6
+elif [ $exit_code -eq 35 ]; then
+    echo -e "\nThe $main_repo is blocked in your current country.\n"
+    exit 35
+fi
+
+git_repo="https://raw.githubusercontent.com"
+
+curl -s --retry 4 $git_repo > /dev/null
+exit_code=$?
+
+if [ $exit_code -eq 6 ]; then
+    echo -e "\nRequest to $git_repo failed. Please check your internet connection.\n"
+    exit 6
+elif [ $exit_code -eq 35 ]; then
+    echo -e "\nThe $git_repo is blocked in your current country.\n"
+    exit 35
+fi
+
+echo -ne "\rapt update ..."
+apt update > /dev/null 2> >(grep -v "apt does not have a stable CLI interface")
+
+charit=-1
+total=19
+start_time=$(date +%s)
+
+_progress() {
+    charit=$((charit + 1)) 
+    percentage=$((charit * 100 / total))
+    echo -ne "\rProgress: $charit/$total ($percentage%)"
+    if [ $percentage -eq 100 ]; then
+        end_time=$(date +%s)
+        elapsed_time=$((end_time - start_time))
+        echo -ne "\rProgress: $charit/$total ($percentage%) Took: $elapsed_time seconds"
     else
-        echo -e "\nNo internet connection. Please check your connection. \nRetrying in 5s...\n"
-        sleep 5
+        echo -ne "\rProgress: $charit/$total ($percentage%)"
     fi
-done
+}
+
+_progress
 
 url="https://raw.githubusercontent.com/nohajc/nohajc.github.io/master/dists/termux/extras/binary-${arch}"
 
@@ -46,19 +90,19 @@ get_version "termux-adb" termux_adb_version_c
 libprotobuf_version_i=$(pkg show libprotobuf-tadb-core 2>/dev/null | grep Version | cut -d ' ' -f 2)
 termux_adb_version_i=$(pkg show termux-adb 2>/dev/null | grep Version | cut -d ' ' -f 2)
 
-# Function to compare versions
+# Function to compare versions without printing anything if the package is already updated
 compare_versions() {
   package_name="$1"
   available_version="$2"
   installed_version="$3"
-
-  if [ "$installed_version" == "$available_version" ]; then
-    echo -e "\n$package_name is already the newest version.\n"
-  else
-    curl -O "$url/${package_name}_${available_version}_${arch}.deb"
-    dpkg -i "${package_name}_${available_version}_${arch}.deb"
+  if [ "$installed_version" != "$available_version" ]; then
+    curl -s -O "$url/${package_name}_${available_version}_${arch}.deb"
+    dpkg -i "${package_name}_${available_version}_${arch}.deb" >/dev/null 2>&1
     rm -f "${package_name}_${available_version}_${arch}.deb"
   fi
+
+  _progress
+
 }
 
 compare_versions "libprotobuf-tadb-core" "$libprotobuf_version_c" "$libprotobuf_version_i"
@@ -87,69 +131,42 @@ packages=(
 for package in "${packages[@]}"; do
     installed=$(apt policy "$package" 2>/dev/null | grep 'Installed' | awk '{print $2}')
     candidate=$(apt policy "$package" 2>/dev/null | grep 'Candidate' | awk '{print $2}')
-    if [ "$installed" == "$candidate" ]; then
-        echo -e "\n$package is already the newest version.\n"
-    else
-        echo -e "\nDownloading $package...\n"
-        apt download "$package"
-        echo -e "\nInstalling $package...\n"
-        dpkg -i "${package}"*.deb
+    if [ "$installed" != "$candidate" ]; then
+        apt download "$package" >/dev/null 2>&1
+        dpkg -i "${package}"*.deb >/dev/null 2>&1
         rm -f "${package}"*.deb
     fi
+
+    _progress
+
 done
 
+
 check_package() {
+    package_name=$1
+    install_cmd=$2
     package_name=$1
     install_cmd=$2
     installed_version=$(pip show "$package_name" 2>/dev/null | grep Version | awk '{print $2}')
     latest_version=$(pip index versions "$package_name" 2>/dev/null | grep 'LATEST:' | awk '{print $2}')
 
     if [ -z "$installed_version" ]; then
-        echo -e "\n$package_name is not installed. Installing...\n"
         eval "$install_cmd -q"
-    else
-        if [ "$installed_version" != "$latest_version" ]; then
-            echo -e "\nThe installed version of $package_name is outdated. \nUpdating...\n"
-            eval "$install_cmd --upgrade -q"
-        else
-            echo -e "\n$package_name is up to date.\n"
-        fi
+    elif [ "$installed_version" != "$latest_version" ]; then
+        eval "$install_cmd --upgrade -q"
     fi
+
+    _progress
+
 }
 
 check_package "pycryptodomex" "pip install pycryptodomex --extra-index-url https://termux-user-repository.github.io/pypi/"
 check_package "requests" "pip install requests"
 
-if [ -f "$PREFIX/bin/mibypass" ]; then    miurl="https://raw.githubusercontent.com/offici5l/MiBypassTool/main/MiBypassTool.py"
-    miv_c=$(curl -s "$miurl" | grep version | grep -oP '(?<=version = ")[^"]+')
-    miv_i=$(grep version "$PREFIX/bin/mibypass" | grep -oP '(?<=version = ")[^"]+')
-    if [ -z "$miv_i" ]; then
-      cmd="2"
-    elif [ "$miv_i" == "$miv_c" ]; then
-      cmd="0"
-    else
-      cmd="1"
-    fi
-else
-    cmd="3"
-fi
+curl -s "https://raw.githubusercontent.com/offici5l/MiBypassTool/main/MiBypassTool.py" -o "$PREFIX/bin/mibypass" && chmod +x "$PREFIX/bin/mibypass"
 
-if [ "$1" == "f" ]; then
-    cmd="3"
-fi
+_progress
 
-if [ "$cmd" == "0" ]; then
-    echo -e "\nMiBypassTool is already the newest \nversion installed: $miv_i.\nLatest available version: $miv_c.\n"
-    printf "\nuse command: \e[1;32mmibypass\e[0m\n\n"
-    exit
-elif [ "$cmd" == "1" ]; then
-    echo -e "\nAn update is available! Updating from version $miv_i to $miv_c...\n"
-elif [ "$cmd" == "2" ]; then
-    echo -e "\nNo version installed. Downloading the latest version: $miv_c...\n"
-elif [ "$cmd" == "3" ]; then
-    echo -e "\nMiBypassTool is being updated now ...\n"
-fi
-
-curl "https://raw.githubusercontent.com/offici5l/MiBypassTool/main/MiBypassTool.py" -o "$PREFIX/bin/mibypass" && chmod +x "$PREFIX/bin/mibypass"
+echo
 
 printf "\nuse command: \e[1;32mmibypass\e[0m\n\n"
